# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="helm"

inherit g-sorcery gs-elpa

DESCRIPTION="Helm is an Emacs incremental and narrowing framework"

HOMEPAGE="https://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/async
	app-emacs/popup
	app-emacs/helm-core"
RDEPEND="app-emacs/async
	app-emacs/popup
	app-emacs/helm-core"
