# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://stable.melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="bind-key"

inherit g-sorcery gs-elpa

DESCRIPTION="A simple way to manage personal keybindings"

HOMEPAGE="http://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
