# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://melpa-stable.milkbox.net/packages/"
SOURCE_TYPE="single"
REALNAME="find-file-in-project"

inherit g-sorcery gs-elpa

DESCRIPTION="Find filedirectory and review DiffPatchCommit efficiently everywhere"

HOMEPAGE="http://melpa-stable.milkbox.net/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/ivy"
RDEPEND="app-emacs/ivy"
