# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="find-file-in-project"

inherit g-sorcery gs-elpa

DESCRIPTION="Find filedirectory and review DiffPatchCommit efficiently"

HOMEPAGE="https://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
