# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="use-package"

inherit g-sorcery gs-elpa

DESCRIPTION="A configuration macro for simplifying your .emacs"

HOMEPAGE="https://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/bind-key"
RDEPEND="app-emacs/bind-key"
