# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://melpa-stable.milkbox.net/packages/"
SOURCE_TYPE="single"
REALNAME="pkg-info"

inherit g-sorcery gs-elpa

DESCRIPTION="Information about packages"

HOMEPAGE="http://melpa-stable.milkbox.net/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/epl"
RDEPEND="app-emacs/epl"
