# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="general"

inherit g-sorcery gs-elpa

DESCRIPTION="Convenience wrappers for keybindings."

HOMEPAGE="https://melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
