# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="xterm-color"

inherit g-sorcery gs-elpa

DESCRIPTION="ANSI, XTERM 256 and Truecolor support"

HOMEPAGE="https://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
