# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="black"
REALVERSION="22.12.0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_7,3_8,3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit gs-pypi

DESCRIPTION="The uncompromising code formatter."

HOMEPAGE="https://github.com/psf/black"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/a6/59/e873cc6807fb62c11131e5258ca15577a3b7452abad08dc49286cf8245e8/black-22.12.0.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="+colorama +d +jupyter +uvloop"
BDEPEND=">=dev-python/click-8.0.0[${PYTHON_USEDEP}]
    >=dev-python/mypy-extensions-0.4.3[${PYTHON_USEDEP}]
    >=dev-python/pathspec-0.9.0[${PYTHON_USEDEP}]
    >=dev-python/platformdirs-2[${PYTHON_USEDEP}]
    >=dev-python/tomli-1.1.0[${PYTHON_USEDEP}]
    >=dev-python/typed-ast-1.4.2[${PYTHON_USEDEP}]
    >=dev-python/typing-extensions-3.10.0.0[${PYTHON_USEDEP}]
    colorama? ( >=dev-python/colorama-0.4.3[${PYTHON_USEDEP}] )
    d? ( >=dev-python/aiohttp-3.7.4[${PYTHON_USEDEP}] )
    jupyter? ( >=dev-python/ipython-7.8.0[${PYTHON_USEDEP}] )
    jupyter? ( >=dev-python/tokenize-rt-3.2.0[${PYTHON_USEDEP}] )
    uvloop? ( >=dev-python/uvloop-0.15.2[${PYTHON_USEDEP}] )"
RDEPEND=">=dev-python/click-8.0.0[${PYTHON_USEDEP}]
    >=dev-python/mypy-extensions-0.4.3[${PYTHON_USEDEP}]
    >=dev-python/pathspec-0.9.0[${PYTHON_USEDEP}]
    >=dev-python/platformdirs-2[${PYTHON_USEDEP}]
    >=dev-python/tomli-1.1.0[${PYTHON_USEDEP}]
    >=dev-python/typed-ast-1.4.2[${PYTHON_USEDEP}]
    >=dev-python/typing-extensions-3.10.0.0[${PYTHON_USEDEP}]
    colorama? ( >=dev-python/colorama-0.4.3[${PYTHON_USEDEP}] )
    d? ( >=dev-python/aiohttp-3.7.4[${PYTHON_USEDEP}] )
    jupyter? ( >=dev-python/ipython-7.8.0[${PYTHON_USEDEP}] )
    jupyter? ( >=dev-python/tokenize-rt-3.2.0[${PYTHON_USEDEP}] )
    uvloop? ( >=dev-python/uvloop-0.15.2[${PYTHON_USEDEP}] )"
