# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="nadvice"

inherit g-sorcery gs-elpa

DESCRIPTION="Forward compatibility for Emacs-24.4s nadvice"

HOMEPAGE="https://elpa.gnu.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
