# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://stable.melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="avy"

inherit g-sorcery gs-elpa

DESCRIPTION="Jump to arbitrary positions in visible text and select text quickly."

HOMEPAGE="http://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
