# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://melpa-stable.milkbox.net/packages/"
SOURCE_TYPE="single"
REALNAME="dash-functional"

inherit g-sorcery gs-elpa

DESCRIPTION="Collection of useful combinators for Emacs Lisp"

HOMEPAGE="http://melpa-stable.milkbox.net/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash"
RDEPEND="app-emacs/dash"
