# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="which-key"

inherit g-sorcery gs-elpa

DESCRIPTION="Display available keybindings in popup"

HOMEPAGE="https://elpa.gnu.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
