# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="lsp-ui"

inherit g-sorcery gs-elpa

DESCRIPTION="UI modules for lsp-mode"

HOMEPAGE="https://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash
	app-emacs/lsp-mode
	app-emacs/markdown-mode"
RDEPEND="app-emacs/dash
	app-emacs/lsp-mode
	app-emacs/markdown-mode"
