# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ace-window"

inherit g-sorcery gs-elpa

DESCRIPTION="Quickly switch windows."

HOMEPAGE="https://elpa.gnu.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/avy"
RDEPEND="app-emacs/avy"
