# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="let-alist"

inherit g-sorcery gs-elpa

DESCRIPTION="Easily let-bind values of an assoc-list by their names"

HOMEPAGE="https://elpa.gnu.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
