# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://melpa-stable.milkbox.net/packages/"
SOURCE_TYPE="single"
REALNAME="projectile"

inherit g-sorcery gs-elpa

DESCRIPTION="Manage and navigate projects in Emacs easily"

HOMEPAGE="http://melpa-stable.milkbox.net/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/pkg-info"
RDEPEND="app-emacs/pkg-info"
