# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="seq"

inherit g-sorcery gs-elpa

DESCRIPTION="Sequence manipulation functions"

HOMEPAGE="http://elpa.gnu.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
