# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="magit-delta"

inherit g-sorcery gs-elpa

DESCRIPTION="Use Delta when displaying diffs in Magit"

HOMEPAGE="https://melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/magit
	app-emacs/xterm-color"
RDEPEND="app-emacs/magit
	app-emacs/xterm-color"
