# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="editorconfig"

inherit g-sorcery gs-elpa

DESCRIPTION="EditorConfig Emacs Plugin"

HOMEPAGE="http://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
