# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="editorconfig"

inherit g-sorcery gs-elpa

DESCRIPTION="EditorConfig Emacs Plugin"

HOMEPAGE="https://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/nadvice"
RDEPEND="app-emacs/nadvice"
