# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="spinner"

inherit g-sorcery gs-elpa

DESCRIPTION="Add spinners and progress-bars to the mode-line for ongoing operations"

HOMEPAGE="https://elpa.gnu.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
