# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="dot-mode"

inherit g-sorcery gs-elpa

DESCRIPTION="minor mode to repeat typing or commands"

HOMEPAGE="https://melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
