# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://melpa-stable.milkbox.net/packages/"
SOURCE_TYPE="tar"
REALNAME="flycheck"

inherit g-sorcery gs-elpa

DESCRIPTION="On-the-fly syntax checking"

HOMEPAGE="http://melpa-stable.milkbox.net/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash
	app-emacs/pkg-info
	app-emacs/let-alist
	app-emacs/seq"
RDEPEND="app-emacs/dash
	app-emacs/pkg-info
	app-emacs/let-alist
	app-emacs/seq"
