# automatically generated by g-sorcery
# please do not edit this file

EAPI=7

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="flycheck"

inherit g-sorcery gs-elpa

DESCRIPTION="On-the-fly syntax checking"

HOMEPAGE="https://stable.melpa.org/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/dash
	app-emacs/pkg-info
	app-emacs/let-alist
	app-emacs/seq"
RDEPEND="app-emacs/dash
	app-emacs/pkg-info
	app-emacs/let-alist
	app-emacs/seq"
