# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="http://melpa-stable.milkbox.net/packages/"
SOURCE_TYPE="single"
REALNAME="helm-projectile"

inherit g-sorcery gs-elpa

DESCRIPTION="Helm integration for Projectile"

HOMEPAGE="http://melpa-stable.milkbox.net/packages/"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/helm
	app-emacs/projectile
	app-emacs/dash"
RDEPEND="app-emacs/helm
	app-emacs/projectile
	app-emacs/dash"
